services:
  api:
    container_name: taguinho_api
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on: 
      - db

  db:
    image: postgres:15-alpine
    container_name: taguinho_db
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes: 
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
